# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarteraExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'WalletConnectWeb3', :git => 'https://github.com/WalletConnect/Web3.swift'
  pod 'HDWalletKit'
  
  pod 'SDWebImage'
  pod 'SDWebImageSVGCoder'
 
  # Pods for CarteraExample

  target 'CarteraExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            config.build_settings['SWIFT_VERSION'] = '5.0'
            if config.base_configuration_reference
              xcconfig_path = config.base_configuration_reference.real_path
              xcconfig = File.read(xcconfig_path)
              xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
              File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
            end
          end
      end
  end
end
